version: '3'
services:
  ros:
    build: .
    environment:
      - "USERNAME=ros"
    volumes:
      - .:/home/ros
    networks:
      - ros_network

  micro_ros_agent1:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico1
    devices:
      - "/dev/pico1:/dev/pico1"
    networks:
      - ros_network
    ports:
      - "8888:8888"
  micro_ros_agent2:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico2
    devices:
      - "/dev/pico2:/dev/pico2"
    networks:
      - ros_network
    ports:
      - "8889:8888"

networks:
  ros_network:
    driver: bridge
