version: '3'
services:
  ros:
    image: ros_container
    container_name: ros_container
    privileged: true
    ipc: host
    network_mode: host
    user: jetson
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./bashrc:/home/ros/.bashrc"
      - "./ros2_ws:/source"
    command: ["/entrypoint.sh"]
    

  micro_ros_agent1:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico1
    devices:
      - "/dev/pico1:/dev/pico1"
    network_mode: "host"
    ipc: host
        
  micro_ros_agent2:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico2
    devices:
      - "/dev/pico2:/dev/pico2"
    network_mode: "host"
    ipc: host
