version: '3'
services:
  ros:
    build: .
    environment:
      - "USERNAME=ros"
    volumes:
      - .:/home/ros
    

  micro_ros_agent1:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico1
    devices:
      - "/dev/pico1:/dev/pico1"
    network_mode: "host"
    ipc: host
        
  micro_ros_agent2:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/pico2
    devices:
      - "/dev/pico2:/dev/pico2"
    network_mode: "host"
    ipc: host
