teleop_node:
  ros__parameters:
    
    axis_linear:  
      x: 1
    scale_linear:
      x: 50.0
    scale_linear_turbo:
      x: 100.0

    axis_angular:  
      yaw: 0
    scale_angular:
      yaw: 50.0
    scale_angular_turbo:
      yaw: 100.0
    enable_turbo_button: 7

joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0